### ISSUE TITLE
Automatically take and host an image

### ISSUE THREAD

**Issue by rememberYou** [rememberYou/emacs-ideas#1]
## Description

This package aims to simplify the process of taking an image and hosting it on a remote service like [postImage](https://postimages.org/). Therefore, based on a single function, the user can either make a screenshot of his current buffer, or host a particular image. Similar to [webpaste](https://github.com/etu/webpaste.el) to host its code.

## Things to Implement [0/2]

- [ ] Use `imagemagick` to take the screenshots, already built-in with GNU Emacs.
- [ ] Allow you to host your image on other services with `curl`.

## Useful links

https://www.emacswiki.org/emacs/ScreenShot
https://superuser.com/questions/777184/upload-image-to-postimage-org-using-curl

**Comment by alphapapa** [comment]
A package was recently added to MELPA for this, see `imgbb`.

**Comment by rememberYou** [comment]
Awesome! Thanks for the information.
