### ISSUE TITLE
Not an issue, but a help hand for setting up hugo-emacs-blog

### ISSUE THREAD

**Issue by OrionRandD** [rememberYou/emacs-ideas#10]
Do you know hugo for emacs blogging?
I'd like a help hand if possible to set up a blog using hugo, emacs and github or gitlab.
I can set up it up only to my localhost, but I am failing to set up hugo to work with my github/gitlab account.
Here are the steps I have taken:
Of course, I have to uncomment the lines in my
init.el

* TODO Ox-hugo 

  Hugo is better than org2blog
  https://gohugo.io/getting-started/quick-start/
  https://zzamboni.org/post/my-emacs-configuration-with-commentary/

  How to set up hugo:
  apt install hugo
  then:
  cd ~/org~/ and issue
  hugo new site blog
  cd ~/org~/blog
  git init
  Then add a theme:
  cd ~/org~/blog/themes/
  git submodule add https://github.com/budparr/gohugo-theme-ananke.git ananke
  cd .. 
  echo 'theme = "ananke"' >> config.toml 
  hugo new posts/my-first-post.md 
  Edit the my-first-post.md
  cd ~/org~/blog
  then start the server
  hugo server -D
  open it in:
  http://localhost:1313/
  in emacs it is "org-hugo"
  M-x org-hugo

hash-plus BEGIN_SRC emacs-lisp

  ;;   (use-package ox-hugo
  ;;    :ensure t   
  ;;    :after ox)

  ;; (require 'ox-hugo)
  ;; (require 'org-hugo-auto-export-mode)

  ;;  (use-package org-capture
  ;;    :ensure nil
  ;;    :config
  ;;     (defun org-hugo-new-subtree-post-capture-template ()
  ;; ;;      "Returns `org-capture' template string for new Hugo post.
  ;; ;;    See `org-capture-templates' for more information."

  ;;      (let* ((title (read-from-minibuffer "Post Title: ")) ;Prompt to enter the post title
  ;; 	 (fname (org-hugo-slug title)))
  ;;        (mapconcat #'identity
  ;; 	       `(,(concat "* TODO " title)
  ;; 		 ":PROPERTIES:"
  ;; 		 ,(concat ":EXPORT_HUGO_BUNDLE: " fname)
  ;; 		 ":EXPORT_FILE_NAME: index"
  ;; 		 ":END:"
  ;; 		 "%?\n")                ;Place the cursor here finally
  ;; 	       "\n")))
  ;;    (add-to-list 'org-capture-templates
  ;; 	     '("o"                ;`org-capture' binding + o
  ;; 	       "Post"
  ;; 	       entry
  ;; 	       ;; It is assumed that below file is present in `org-directory'
  ;; 	       ;; and that it has an "Ideas" heading. It can even be a
  ;; 	       ;; symlink pointing to the actual location of all-posts.org!
  ;; 	       (file+datetree (concat org-directory "~/blog/content/posts/my-post.org")
  ;; "* TODO %^{Description}  %^g\n%?\nAdded: %U")
  ;; 	       (function org-hugo-new-subtree-post-capture-template))))

hash-plus END_SRC

**Comment by rememberYou** [comment]
Hello,

Unfortunatelly, I don't use `ox-hugo`, but [many threads](https://www.reddit.com/search/?q=hugo%20emacs) are related to it on Reddit. Maybe, can you start to check them and see if you find a solution to your issue?

In the opposite case, I invite you to ask your question on IRC to the `#emacs` channel. I'm sure that someone would help you to figure it out.

**NOTE:**  if you really don't find any answer on Reddit and on IRC, I will try to check the issue more deeper 😊

**Comment by OrionRandD** [comment]
I have researched the issue, but could not find a solution.
As I said: "I can set up the localhost", but have not been able to
set up an external blog to start with.
If you have any spared time in the future, I'd be grateful if you 
can look the issue.
Also, if you use any package other package for blogging using emacs
I'd like to know your experience on that.

**Comment by rememberYou** [comment]
Alright, did you already try to ask your question in `#emacs` with [freenode](https://webchat.freenode.net/)?

**Comment by OrionRandD** [comment]
Yeah. They say the same: "google it"
But, you do not need to rush to into it.
Just when you have a spare time.
This easy-hugo seems good...

**Comment by OrionRandD** [comment]
https://zzamboni.org/post/my-emacs-configuration-with-commentary/#blogging-with-hugo
https://gohugo.io/
https://gohugo.io/tools/editors/#emacs
some websources

**Comment by OrionRandD** [comment]
https://vimeo.com/48163827
https://invidio.us/watch?v=wSeTic9obKw

**Comment by kaushalmodi** [comment]
@OrionRandD

I arbitrarily searched for "ox-hugo" in Github issues to see if anyone was facing problems with it .. and found this.

From what I understand, you can generate pages locally, but need help deploying them in public. IMO deployment using Netlify (free) is the best/easiest and after that comes deployment using Gitlab Pages, and GitHub based deployment is the last option.

Official help pages:

- [Deploying Hugo generated site on Netlify][1]
- [Deploying Hugo generated site via Gitlab Pages][2]

Furthermore, if you google combinations of "Hugo", "Netlify", and "Gitlab Pages", you will find many blog posts covering the same topic.

If you are still at a loss, mention the issue you are seeing on https://discourse.gohugo.io/. There are many awesome folks in the Hugo community; a learned a lot from them.

And of course, if you face any trouble/confusion with using `ox-hugo`, don't hesitate to open an issue at https://github.com/kaushalmodi/ox-hugo/issues.


---

PS: I see that you wrote your Org snippet as below:

...
hash-plus BEGIN_SRC emacs-lisp

;; (use-package ox-hugo
;; :ensure t
...

You don't have to do that! Use the markdown code block syntax :)

If you type:

````
```
...
#+BEGIN_SRC emacs-lisp

;; (use-package ox-hugo
;; :ensure t
...
```
````

you will get:

```
...
#+BEGIN_SRC emacs-lisp

;; (use-package ox-hugo
;; :ensure t
...
```

[1]: https://gohugo.io/hosting-and-deployment/hosting-on-netlify/
[2]: https://gohugo.io/hosting-and-deployment/hosting-on-gitlab/

**Comment by OrionRandD** [comment]
@kaushalmodi  thx a lot for the links and suggestion on using netify. I wll have a look on that :)

**Comment by rememberYou** [comment]
@kaushalmodi thank you for the help, I allow myself to close this issue ☺️
