### ISSUE TITLE
Write a fast terminal emulator

### ISSUE THREAD

**Issue by rememberYou** [rememberYou/emacs-ideas#4]
## Description

I find `ansi-term` slow compared to other terminator emulators. The idea is to optimize it with some modifications.

## Things to Implement [0/1]

- [ ] Use FFI and [libtsm](http://www.freedesktop.org/wiki/Software/kmscon/libtsm/).

## Useful Links

http://www.reddit.com/r/vim/comments/30btwx/neovim_now_has_a_full_terminal_emulator_mode_i/
https://github.com/akermu/emacs-libvterm

**Comment by thblt** [comment]
We have vterm. I guess you can close this one.

**Comment by Naheel-Azawy** [comment]
@thblt vterm is no where near any normal terminal emulator. I tried many times to live with it but it's still unusable for things like tui programs or anything that requires fast changes.

**Comment by thblt** [comment]
@Naheel-Azawy My understanding is that vterm's limitations are implementation issues, but that "a fast terminal emulator" is now past the "idea" stage. If I'm wrong, feel free to reopen I guess.

**Comment by Naheel-Azawy** [comment]
@thblt that's a good point. Then let's hope that vterm gets magically improved
